name: CI - Frontend

on:
  push:
  pull_request:


jobs:
  build-shell:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/shell
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build

  build-mfe-orders:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/mfe-orders
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build

  build-mfe-admin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/mfe-admin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build
